name: Build and push dockerized services
on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: 'version'
        default: 'latest'
jobs:
  docker-service:
    name: Build dockerized services
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: string
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ github.repository }}
      - name: Build and push functions
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ steps.string.outputs.lowercase }}:${{ github.event.inputs.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}